import { createContext, useContext, useState } from 'react'

const strings = {
  en: {
    // App - shared header/footer
    'app.helpBanner': 'Need help? Call 1-800-222-6868',
    'app.secure': 'Secure & Encrypted',
    'app.footer': '1-800Accountant Entity Formation Services',
    'app.ssl': '256-bit SSL Encryption',
    'app.guarantee': 'Money-Back Guarantee',

    // Language dropdown
    'lang.label': 'EN',
    'lang.en': 'English',
    'lang.es': 'Español',

    // Nav buttons
    'nav.back': 'Back',
    'nav.letsGo': "Let's Go",
    'nav.findSavings': 'Find My Savings',
    'nav.startSaving': 'Start Saving on Taxes',
    'nav.seePotential': 'See My Tax Savings Potential',
    'nav.continue': 'Continue',
    'nav.launch': 'Launch {name}!',

    // Savings banner
    'banner.label': 'Your Estimated Tax Savings',
    'banner.readyPill': 'Savings Ready to Unlock',
    'banner.warningPill': 'Savings May Be Reduced',
    'banner.lessPlans': '${amount} less than Covered',
    'banner.applyNote': "We'll apply these savings directly to your tax return and books.",
    'banner.corpWarning': 'A C-Corporation is generally not the optimal structure for 1099 contractors and gig workers. An LLC typically provides greater tax savings and flexibility. Consider switching to LLC to maximize your estimated savings.',
    'banner.lowerPlanWarning': 'Switching to the Covered plan unlocks an additional ${amount}/yr in estimated savings.',

    // Loading screen
    'loading.scanning': 'Identifying tax savings for {state} {industry}...',
    'loading.scanSub': "We're scanning {state}-specific deductions and tax strategies available to {industry} so we can maximize what you keep.",
    'loading.found': 'Tax savings opportunities found!',
    'loading.foundSub': "We've identified {state}-specific savings for {industry}. Let's set your business up to capture them.",

    // Success screen
    'success.title': 'Order Submitted!',
    'success.sub': 'Your {name} formation is being processed.',
    'success.emailNote': 'A confirmation email has been sent to {email}.',
    'success.progressTitle': 'Progress',
    'success.status1': 'Order Submitted',
    'success.status1Sub': 'Your formation request has been received',
    'success.status1SubExisting': 'Your order has been received',
    'success.status2': 'Filed with Government',
    'success.status2Sub': 'Your business is being registered with the government',
    'success.status3': 'Onboarding Call',
    'success.status3Sub': 'Meet with your advisor to get your books and taxes set up',
    'success.status4': 'Tax Savings Begins!',
    'success.status4Sub': 'Your savings are applied to your tax return and books',
    'success.schedulerTitle': 'Schedule Your Onboarding Call',
    'success.schedulerDesc': 'Meet with your advisor approximately 20 days after formation to get bookkeeping, tax prep, and compliance running smoothly for {name}.',
    'success.dateLabel': 'Preferred Date',
    'success.timeLabel': 'Preferred Time',
    'success.confirmBtn': 'Confirm Onboarding Call',
    'success.calendarNote': "We'll send a calendar invite to {email} with your call details.",
    'success.agentBtn': 'Set Up Your Registered Agent',
    'success.newFormation': 'Start a new formation',

    // Registered agent back link
    'agent.backToOrder': 'Back to Order Confirmation',

    // Landing page
    'landing.badge': 'Built exclusively for 1099 contractors',
    'landing.headline1': "You're a",
    'landing.headline2': 'Gig Worker.',
    'landing.headline3': "You're a business.",
    'landing.sub1': 'You just might not know it yet.',
    'landing.sub2': "We don't just form your business — we set it up",
    'landing.sub2b': 'right',
    'landing.sub2c': 'with an accountant so you',
    'landing.sub2d': 'actually save money on taxes',
    'landing.sub2e': ". That's the whole point.",
    'landing.ctaPrimary': 'Get My Savings Started',
    'landing.ctaSecondary': 'See How It Works',
    'landing.trust1': 'No surprise fees',
    'landing.trust2': '4.8/5 from 10,000+ clients',
    'landing.trust3': 'Setup in under 10 minutes',
    'landing.stat1': '$7,200',
    'landing.stat1Sub': 'Average self-employment tax saved per year',
    'landing.stat2': '10,000+',
    'landing.stat2Sub': '1099 contractors trust 1-800Accountant',
    'landing.stat3': '30%+',
    'landing.stat3Sub': 'Average effective tax rate reduction',
    'landing.navHow': 'How It Works',
    'landing.navWhy': 'Why Us',
    'landing.navPricing': 'Pricing',
    'landing.navPhone': '(800) 222-6868',
    'landing.navCta': 'Get Started Free',

    // ProgressBar
    'progress.s1': 'Business Structure',
    'progress.s2': 'Address',
    'progress.s3': 'People',
    'progress.s4': 'Tax Savings Started',
    'progress.s5': 'Savings Unlocked',
    'progress.stepOf': 'Step {n} of {total}',

    // BusinessBasicsStep
    'basics.badge1': 'Built for 1099 Contractors',
    'basics.badge2': 'Optimized for Gig Workers',
    'basics.title': "Don't Let Taxes Eat Your Side Income",
    'basics.sub': "If you're making money on the side, you shouldn't overpay. We'll file your taxes, manage your books, and help you keep more of what you earn.",
    'basics.firstName': 'First Name',
    'basics.lastName': 'Last Name',
    'basics.email': 'Email Address',
    'basics.phone': 'Phone Number',
    'basics.firstPH': 'First name',
    'basics.lastPH': 'Last name',
    'basics.emailPH': 'you@example.com',
    'basics.phonePH': '(555) 555-5555',
    'basics.ssoOr': 'or sign in to auto-fill',
    'basics.google': 'Continue with Google',
    'basics.greeting': "Nice to meet you, {name}! Let's find your tax savings.",

    // SideHustleStep
    'hustle.title': "Let's find your",
    'hustle.titleHighlight': 'hidden savings',
    'hustle.sub': "We'll also file your taxes and handle your books — so you can focus on earning.",
    'hustle.q1': 'Is your side gig or hustle up and running?',
    'hustle.opt1Label': "Yes, it's up and running",
    'hustle.opt1Desc': "I'm actively earning income from my side gig or business.",
    'hustle.opt2Label': "Not yet — I'm just starting",
    'hustle.opt2Desc': "I'm planning to start soon and want to set it up right.",
    'hustle.revenueYes': 'How much do you bring in a year on your side hustle or business?',
    'hustle.revenueNo': 'How much do you expect to bring in?',
    'hustle.rev1': 'Under $25k',
    'hustle.rev2': '$25k–$50k',
    'hustle.rev3': '$50k–$100k',
    'hustle.rev4': '$100k–$250k',
    'hustle.rev5': '$250k+',

    // LocationIndustryStep
    'location.titleYes': 'Where is your business based?',
    'location.titleNo': 'Where are you planning to set up?',
    'location.subYes': "We'll find the tax deductions and strategies available in your state and industry.",
    'location.subNo': "We'll identify state-specific savings opportunities before you even get started — and apply them directly to your tax return and books.",
    'location.stateLabel': 'State',
    'location.statePH': 'Select your state',
    'location.industryLabel': 'What industry are you in?',

    // EntityQuestionStep
    'entity.title1': 'The right business setup can',
    'entity.title2': 'save you thousands',
    'entity.title3': 'in taxes',
    'entity.sub': "Most gig workers pay more in taxes than they should because they haven't set up their business properly. Let's unlock your savings — and we'll make sure every dollar is applied when we handle your taxes and books.",
    'entity.stat1': '$7,200',
    'entity.stat1Label': 'Avg. Tax Savings',
    'entity.stat2': '30%+',
    'entity.stat2Label': 'Tax Reduction',
    'entity.stat3': '100+',
    'entity.stat3Label': 'Deductions Unlocked',
    'entity.q1': 'Are you formally registered with the state?',
    'entity.opt1Title': "No — let's set it up and start saving",
    'entity.opt1Desc': "I haven't formally registered yet. I want to set up the right structure to maximize my tax savings.",
    'entity.opt1Badge': 'Best savings for 1099 contractors & gig workers',
    'entity.opt2Title': 'Yes — show me how much more I can save',
    'entity.opt2Desc': "I'm already registered. I want to find the additional savings I might be leaving on the table.",
    'entity.opt2Badge': 'Already formally registered',
    'entity.nameYesLabel': 'What is your business name?',
    'entity.nameNoLabel': 'What do you want to call your business?',
    'entity.nameNoHelper': "We'll check with the Secretary of State to make sure your name is available.",
    'entity.namePHYes': 'e.g. Sunrise Consulting LLC',
    'entity.namePHNo': 'e.g. Sunrise Consulting Group',
    'entity.timelineLabel': 'When are you looking to get up and running?',
    'entity.timelineHelper': "The sooner you're set up, the sooner you start saving on taxes.",
    'entity.tl1': 'As soon as possible',
    'entity.tl1Sub': "Every month you wait is money left on the table. Lock in your savings now.",
    'entity.tl2': 'In about a month',
    'entity.tl2Sub': "We'll get your setup locked in so your tax savings kick in fast.",
    'entity.tl3': 'In the next few months',
    'entity.tl3Sub': "Smart to plan ahead. We'll make sure your business is optimized from day one.",
    'entity.helpText': "Not sure if you've already formed a business?",
    'entity.helpCall': 'Call 1-800-222-6868',
    'entity.helpEnd': "and we'll help you figure it out.",

    // EntityTypeStep
    'entityType.title': 'Your Optimized Business Structure',
    'entityType.sub': "We've determined the optimized business setup for you.",
    'entityType.badge': 'Maximized Tax Savings',
    'entityType.stateLabel': 'State of Formation',
    'entityType.statePH': 'Select a state...',
    'entityType.stateHelper': 'Most businesses form their LLC in the same state they operate in. Unless you have a specific reason, we recommend keeping it simple.',

    // CompanyInfoStep
    'company.title': 'Where will {name} operate from?',
    'company.sub': 'We need a physical address for your business. This will be used on your formation documents.',
    'company.street': 'Street Address',
    'company.suite': 'Suite / Unit',
    'company.city': 'City',
    'company.state': 'State',
    'company.zip': 'ZIP Code',
    'company.streetPH': '123 Main St',
    'company.suitePH': 'Optional',
    'company.cityPH': 'City',
    'company.statePH': 'State',
    'company.zipPH': 'ZIP Code',
    'company.helper': "This can be your home address, office, or wherever you'll be running things from. You can always update it later.",

    // MembersStep
    'members.personN': 'Person {n}',
    'members.remove': 'Remove',
    'members.firstName': 'First Name',
    'members.lastName': 'Last Name',
    'members.titleRole': 'Title / Role',
    'members.email': 'Email',
    'members.ownership': 'Ownership %',
    'members.firstPH': 'First name',
    'members.lastPH': 'Last name',
    'members.titlePH': 'Select title...',
    'members.emailPH': 'email@example.com',
    'members.addAnother': 'Add Another Person',
    'members.ownershipValid': 'Ownership totals 100%.',
    'members.ownershipInvalid': 'Ownership must equal 100%. Current total: {total}%.',
    'members.sub': 'Add the people who will be part of your {entity}.',

    // PackageStep
    'package.title': 'Get Your Tax Savings Started',
    'package.per6mo': 'every 6 months',
    'package.annualNote': '${price}/yr — first payment after formation + state filing fees',
    'package.savingsBadge': 'Estimated Tax Savings ~${amount}',
    'package.recommended': 'Recommended',
    'package.selected': 'Selected',
    'package.selectPlan': 'Select Plan',
    'package.filingFeeNote': '{state} state filing fee: ${fee} — due today. Your plan subscription starts after your entity is filed.',
    'package.comparePlans': 'Compare Plans in Detail',
    'package.colFeature': 'Feature',
    'package.colIndependent': 'Independent',
    'package.colCovered': 'Covered',

    // CheckoutStep
    'checkout.title': 'Checkout',
    'checkout.sub': 'Complete your order to begin the formation process.',
    'checkout.editInfo': 'Edit Your Information',
    'checkout.editInfoSub': 'Review and update your business details',
    'checkout.orderSummary': 'Order Summary',
    'checkout.stateFee': '{state} State Filing Fee',
    'checkout.dueToday': 'Due today',
    'checkout.billedAfter': '${semi}/6mo (${annual}/yr) — billed after formation',
    'checkout.firstPayment': '${annual}/yr — first payment due today',
    'checkout.dueTodayLabel': 'Due Today',
    'checkout.orCard': 'or pay with card',
    'checkout.nameOnCard': 'Name on Card',
    'checkout.namePH': 'Full name as shown on card',
    'checkout.sameAsOwner': 'Same as primary owner',
    'checkout.cardDetails': 'Card Details',
    'checkout.billingAddress': 'Billing Address',
    'checkout.sameAsAddress': 'Same as business address',
    'checkout.secureNote': 'Your payment information is secured with 256-bit SSL encryption.',
    'checkout.modal.title': 'Edit Your Information',
    'checkout.modal.bizStructure': 'Business Structure & State',
    'checkout.modal.bizAddress': 'Business Address',
    'checkout.modal.entityType': 'Entity Type',
    'checkout.modal.stateFormation': 'State of Formation',
    'checkout.modal.entityName': 'Entity Name',
    'checkout.modal.address': 'Address',
    'checkout.modal.plan': 'Plan',
    'checkout.modal.planCost': 'Plan Cost',
    'checkout.modal.stateFee': 'State Filing Fee',
    'checkout.modal.terms': 'By submitting this order, you agree to our Terms of Service and Privacy Policy.',
    'checkout.modal.done': 'Done',
    'checkout.modal.personN': 'Person {n}',
    'checkout.modal.title2': 'Title',
    'checkout.modal.email': 'Email',
    'checkout.modal.ownership': 'Ownership',
    'checkout.modal.selectedPlan': 'Selected Plan',

    // TaxSavingsStep
    'tax.titleResults': 'Your estimated tax savings',
    'tax.titleInitial': "Let's find your hidden tax savings",
    'tax.subResults': 'Based on the income and details you provided.',
    'tax.subEstimate': "Answer 3 quick questions so we can estimate your unlocked savings.",
    'tax.subDefault': "Answer 3 quick questions and we'll estimate how much more you could save.",
    'tax.annualSavings': 'Estimated Annual Savings',
    'tax.seSavings': 'Self-Employment Tax Savings',
    'tax.deductionSavings': 'Additional Deduction Savings',
    'tax.revenueYes': 'How much do you bring in a year on your 1099, side hustle or gig (outside your W-2)?',
    'tax.revenueNo': 'How much do you expect to bring in a year on your 1099, side hustle or gig (outside your W-2)?',
    'tax.revenueDefault': 'How much do you bring in a year outside your W-2?',
    'tax.teamLabel': 'How many people work for you?',
    'tax.bracketLabel': 'Effective Tax Bracket',
    'tax.bracketHelper': "This is typically 25%. We've estimated this for you.",
    'tax.editAssumptions': 'Edit Assumptions',
    'tax.calculateBtn': 'Calculate My Tax Savings',
    'tax.lockBtn': 'Lock In These Savings',
    'tax.unlockBtn': 'Unlock Tax Savings',
    'tax.updateBtn': 'Update My Savings',
    'tax.back': 'Back',
    'tax.scheduler.title': 'Schedule Your Tax Savings Consultation',
    'tax.scheduler.sub': 'Meet with a Small Business Tax Consultant to learn how to unlock up to',
    'tax.scheduler.subEnd': '/yr in savings.',
    'tax.scheduler.advisorTitle': 'In your free consultation, your advisor will:',
    'tax.scheduler.i1': 'Review your current business structure and tax situation',
    'tax.scheduler.i2': 'Identify self-employment tax reduction strategies',
    'tax.scheduler.i3': 'Uncover deductions you may be missing',
    'tax.scheduler.i4': 'Build a personalized plan to maximize your savings',
    'tax.scheduler.dateLabel': 'Preferred Date',
    'tax.scheduler.timeLabel': 'Preferred Time',
    'tax.scheduler.confirmBtn': 'Confirm Consultation',
    'tax.scheduler.confirmNote': 'A Small Business Tax Consultant will reach out to confirm your appointment.',
    'tax.scheduler.back': 'Back to Savings Estimate',

    // NonProfitScheduleStep
    'nonprofit.title': "Let's Talk About Your Non-Profit",
    'nonprofit.sub': "Non-profit formation has unique requirements — from tax-exempt status to board structure. We'd love to learn more about your goals and guide you through the process.",
    'nonprofit.coverTitle': "In your free consultation, we'll cover:",
    'nonprofit.i1': "Your organization's mission and goals",
    'nonprofit.i2': "Tax-exempt status requirements (501(c)(3), etc.)",
    'nonprofit.i3': "Board structure and governance",
    'nonprofit.i4': "State-specific filing requirements",
    'nonprofit.i4State': "State-specific filing requirements for {state}",
    'nonprofit.i5': "A personalized formation plan and timeline",
    'nonprofit.scheduleBtn': 'Schedule a Free Consultation',
    'nonprofit.orCall': 'or call us directly',
    'nonprofit.callBtn': 'Call 1-800-222-6868',
    'nonprofit.back': 'Back to Entity Selection',

    // RegisteredAgentStep
    'agent.title': 'Registered Agent',
    'agent.sub': 'Every business needs a registered agent to receive legal documents on its behalf.',
    'agent.useOursTitle': 'Use Our Service',
    'agent.useOursPrice': '$99/yr',
    'agent.useOursDesc': "We'll serve as your registered agent for $99 a year, billed annually after formation.",
    'agent.recommended': 'Recommended',
    'agent.ownTitle': "I'll Provide My Own",
    'agent.ownDesc': "Designate your own registered agent. Must have a physical address in the state of formation.",
    'agent.serviceTitle': 'Our Registered Agent Service Includes:',
    'agent.si1': 'Dedicated physical address in your state of formation',
    'agent.si2': 'Receive and forward all legal correspondence',
    'agent.si3': 'Same-day digital notification of served documents',
    'agent.si4': 'Compliance reminders for annual reports & deadlines',
    'agent.si5': 'Online dashboard to view all documents',
    'agent.agentName': 'Agent Name',
    'agent.physAddr': 'Physical Address',
    'agent.noPO': '(No P.O. boxes)',
    'agent.agentNamePH': 'Full name or company name',
    'agent.streetPH': 'Street address',
    'agent.suitePH': 'Suite / Unit',
    'agent.cityPH': 'City',
    'agent.statePH': 'State',
    'agent.zipPH': 'ZIP Code',
    'agent.confirmBtn': 'Confirm Registered Agent',
  },

  es: {
    // App - shared header/footer
    'app.helpBanner': '¿Necesitas ayuda? Llama al 1-800-222-6868',
    'app.secure': 'Seguro y Encriptado',
    'app.footer': 'Servicios de Formación de Entidades 1-800Accountant',
    'app.ssl': 'Cifrado SSL de 256 bits',
    'app.guarantee': 'Garantía de Devolución de Dinero',

    // Language dropdown
    'lang.label': 'ES',
    'lang.en': 'English',
    'lang.es': 'Español',

    // Nav buttons
    'nav.back': 'Atrás',
    'nav.letsGo': 'Comenzar',
    'nav.findSavings': 'Encontrar Mis Ahorros',
    'nav.startSaving': 'Comenzar a Ahorrar en Impuestos',
    'nav.seePotential': 'Ver Mi Potencial de Ahorro Fiscal',
    'nav.continue': 'Continuar',
    'nav.launch': '¡Lanzar {name}!',

    // Savings banner
    'banner.label': 'Tu Ahorro Fiscal Estimado',
    'banner.readyPill': 'Ahorros Listos para Desbloquear',
    'banner.warningPill': 'Los Ahorros Pueden Reducirse',
    'banner.lessPlans': '${amount} menos que Cubierto',
    'banner.applyNote': 'Aplicaremos estos ahorros directamente a tu declaración de impuestos y contabilidad.',
    'banner.corpWarning': 'Una Corporación C generalmente no es la estructura óptima para contratistas 1099 y trabajadores independientes. Una LLC típicamente ofrece mayores ahorros fiscales y flexibilidad. Considera cambiar a LLC para maximizar tus ahorros estimados.',
    'banner.lowerPlanWarning': 'Cambiar al plan Cubierto desbloquea ${amount}/año adicional en ahorros estimados.',

    // Loading screen
    'loading.scanning': 'Identificando ahorros fiscales para {state} {industry}...',
    'loading.scanSub': 'Estamos analizando las deducciones y estrategias fiscales específicas de {state} disponibles para {industry} para maximizar lo que conservas.',
    'loading.found': '¡Oportunidades de ahorro fiscal encontradas!',
    'loading.foundSub': 'Hemos identificado ahorros específicos de {state} para {industry}. Configuremos tu negocio para aprovecharlos.',

    // Success screen
    'success.title': '¡Pedido Enviado!',
    'success.sub': 'La formación de {name} está siendo procesada.',
    'success.emailNote': 'Se ha enviado un correo de confirmación a {email}.',
    'success.progressTitle': 'Progreso',
    'success.status1': 'Pedido Enviado',
    'success.status1Sub': 'Tu solicitud de formación ha sido recibida',
    'success.status1SubExisting': 'Tu pedido ha sido recibido',
    'success.status2': 'Registrado con el Gobierno',
    'success.status2Sub': 'Tu negocio está siendo registrado con el gobierno',
    'success.status3': 'Llamada de Incorporación',
    'success.status3Sub': 'Reúnete con tu asesor para configurar tu contabilidad e impuestos',
    'success.status4': '¡Los Ahorros Fiscales Comienzan!',
    'success.status4Sub': 'Tus ahorros se aplican a tu declaración de impuestos y contabilidad',
    'success.schedulerTitle': 'Agenda Tu Llamada de Incorporación',
    'success.schedulerDesc': 'Reúnete con tu asesor aproximadamente 20 días después de la formación para poner en marcha la contabilidad, preparación de impuestos y cumplimiento para {name}.',
    'success.dateLabel': 'Fecha Preferida',
    'success.timeLabel': 'Hora Preferida',
    'success.confirmBtn': 'Confirmar Llamada de Incorporación',
    'success.calendarNote': 'Enviaremos una invitación de calendario a {email} con los detalles de tu llamada.',
    'success.agentBtn': 'Configurar Tu Agente Registrado',
    'success.newFormation': 'Iniciar una nueva formación',

    // Registered agent back link
    'agent.backToOrder': 'Volver a Confirmación de Pedido',

    // Landing page
    'landing.badge': 'Construido exclusivamente para contratistas 1099',
    'landing.headline1': 'Eres un',
    'landing.headline2': 'Trabajador Independiente.',
    'landing.headline3': 'Eres un negocio.',
    'landing.sub1': 'Quizás aún no lo sabes.',
    'landing.sub2': 'No solo formamos tu negocio — lo configuramos',
    'landing.sub2b': 'correctamente',
    'landing.sub2c': 'con un contador para que',
    'landing.sub2d': 'realmente ahorres dinero en impuestos',
    'landing.sub2e': '. Ese es el objetivo.',
    'landing.ctaPrimary': 'Comenzar a Ahorrar',
    'landing.ctaSecondary': 'Ver Cómo Funciona',
    'landing.trust1': 'Sin costos sorpresa',
    'landing.trust2': '4.8/5 de más de 10,000 clientes',
    'landing.trust3': 'Configuración en menos de 10 minutos',
    'landing.stat1': '$7,200',
    'landing.stat1Sub': 'Promedio de impuesto de trabajo independiente ahorrado por año',
    'landing.stat2': '10,000+',
    'landing.stat2Sub': 'contratistas 1099 confían en 1-800Accountant',
    'landing.stat3': '30%+',
    'landing.stat3Sub': 'Reducción promedio de tasa impositiva efectiva',
    'landing.navHow': 'Cómo Funciona',
    'landing.navWhy': 'Por Qué Nosotros',
    'landing.navPricing': 'Precios',
    'landing.navPhone': '(800) 222-6868',
    'landing.navCta': 'Comenzar Gratis',

    // ProgressBar
    'progress.s1': 'Estructura del Negocio',
    'progress.s2': 'Dirección',
    'progress.s3': 'Personas',
    'progress.s4': 'Ahorros Fiscales Iniciados',
    'progress.s5': 'Ahorros Desbloqueados',
    'progress.stepOf': 'Paso {n} de {total}',

    // BusinessBasicsStep
    'basics.badge1': 'Para Contratistas 1099',
    'basics.badge2': 'Optimizado para Trabajadores Independientes',
    'basics.title': 'No Dejes que los Impuestos se Coman tus Ingresos',
    'basics.sub': 'Si estás ganando dinero extra, no deberías pagar de más. Presentaremos tus impuestos, manejaremos tu contabilidad y te ayudaremos a conservar más de lo que ganas.',
    'basics.firstName': 'Nombre',
    'basics.lastName': 'Apellido',
    'basics.email': 'Correo Electrónico',
    'basics.phone': 'Número de Teléfono',
    'basics.firstPH': 'Nombre',
    'basics.lastPH': 'Apellido',
    'basics.emailPH': 'tu@ejemplo.com',
    'basics.phonePH': '(555) 555-5555',
    'basics.ssoOr': 'o inicia sesión para autocompletar',
    'basics.google': 'Continuar con Google',
    'basics.greeting': '¡Encantado de conocerte, {name}! Encontremos tus ahorros fiscales.',

    // SideHustleStep
    'hustle.title': 'Encontremos tus',
    'hustle.titleHighlight': 'ahorros ocultos',
    'hustle.sub': 'También presentaremos tus impuestos y manejaremos tu contabilidad — para que puedas enfocarte en generar ingresos.',
    'hustle.q1': '¿Tu trabajo independiente o negocio está en marcha?',
    'hustle.opt1Label': 'Sí, ya está funcionando',
    'hustle.opt1Desc': 'Estoy generando ingresos activamente de mi trabajo independiente o negocio.',
    'hustle.opt2Label': 'Todavía no — estoy comenzando',
    'hustle.opt2Desc': 'Planeo comenzar pronto y quiero configurarlo correctamente.',
    'hustle.revenueYes': '¿Cuánto generas al año con tu trabajo independiente o negocio?',
    'hustle.revenueNo': '¿Cuánto esperas generar?',
    'hustle.rev1': 'Menos de $25k',
    'hustle.rev2': '$25k–$50k',
    'hustle.rev3': '$50k–$100k',
    'hustle.rev4': '$100k–$250k',
    'hustle.rev5': '$250k+',

    // LocationIndustryStep
    'location.titleYes': '¿Dónde está ubicado tu negocio?',
    'location.titleNo': '¿Dónde planeas establecerte?',
    'location.subYes': 'Encontraremos las deducciones fiscales y estrategias disponibles en tu estado e industria.',
    'location.subNo': 'Identificaremos oportunidades de ahorro específicas de tu estado antes de que empieces — y las aplicaremos directamente a tu declaración de impuestos y contabilidad.',
    'location.stateLabel': 'Estado',
    'location.statePH': 'Selecciona tu estado',
    'location.industryLabel': '¿En qué industria trabajas?',

    // EntityQuestionStep
    'entity.title1': 'La estructura correcta de negocio puede',
    'entity.title2': 'ahorrarte miles',
    'entity.title3': 'en impuestos',
    'entity.sub': 'La mayoría de los trabajadores independientes pagan más impuestos de lo necesario porque no han configurado su negocio correctamente. Descubramos tus ahorros — y nos aseguraremos de que cada dólar se aplique cuando manejemos tus impuestos y contabilidad.',
    'entity.stat1': '$7,200',
    'entity.stat1Label': 'Ahorro Fiscal Promedio',
    'entity.stat2': '30%+',
    'entity.stat2Label': 'Reducción de Impuestos',
    'entity.stat3': '100+',
    'entity.stat3Label': 'Deducciones Disponibles',
    'entity.q1': '¿Estás registrado formalmente con el estado?',
    'entity.opt1Title': 'No — configurémoslo y empecemos a ahorrar',
    'entity.opt1Desc': 'Aún no me he registrado formalmente. Quiero establecer la estructura correcta para maximizar mis ahorros fiscales.',
    'entity.opt1Badge': 'Mejor ahorro para contratistas 1099 y trabajadores independientes',
    'entity.opt2Title': 'Sí — muéstrame cuánto más puedo ahorrar',
    'entity.opt2Desc': 'Ya estoy registrado. Quiero encontrar los ahorros adicionales que podría estar dejando ir.',
    'entity.opt2Badge': 'Ya registrado formalmente',
    'entity.nameYesLabel': '¿Cuál es el nombre de tu negocio?',
    'entity.nameNoLabel': '¿Cómo quieres llamar a tu negocio?',
    'entity.nameNoHelper': 'Verificaremos con la Secretaría de Estado para asegurarnos de que el nombre esté disponible.',
    'entity.namePHYes': 'ej. Consultoría Sunrise LLC',
    'entity.namePHNo': 'ej. Grupo Consultoría Sunrise',
    'entity.timelineLabel': '¿Cuándo planeas estar listo para operar?',
    'entity.timelineHelper': 'Cuanto antes estés configurado, antes empezarás a ahorrar en impuestos.',
    'entity.tl1': 'Lo antes posible',
    'entity.tl1Sub': 'Cada mes que esperas es dinero que dejas sobre la mesa. Asegura tus ahorros ahora.',
    'entity.tl2': 'En aproximadamente un mes',
    'entity.tl2Sub': 'Configuraremos todo para que tus ahorros fiscales comiencen rápidamente.',
    'entity.tl3': 'En los próximos meses',
    'entity.tl3Sub': 'Es inteligente planificar con anticipación. Nos aseguraremos de que tu negocio esté optimizado desde el primer día.',
    'entity.helpText': '¿No estás seguro si ya has formado un negocio?',
    'entity.helpCall': 'Llama al 1-800-222-6868',
    'entity.helpEnd': 'y te ayudaremos a resolverlo.',

    // EntityTypeStep
    'entityType.title': 'Tu Estructura de Negocio Optimizada',
    'entityType.sub': 'Hemos determinado la configuración de negocio óptima para ti.',
    'entityType.badge': 'Ahorro Fiscal Maximizado',
    'entityType.stateLabel': 'Estado de Formación',
    'entityType.statePH': 'Selecciona un estado...',
    'entityType.stateHelper': 'La mayoría de las empresas forman su LLC en el mismo estado donde operan. A menos que tengas una razón específica, recomendamos mantenerlo simple.',

    // CompanyInfoStep
    'company.title': '¿Desde dónde operará {name}?',
    'company.sub': 'Necesitamos una dirección física para tu negocio. Se usará en tus documentos de formación.',
    'company.street': 'Dirección',
    'company.suite': 'Suite / Unidad',
    'company.city': 'Ciudad',
    'company.state': 'Estado',
    'company.zip': 'Código Postal',
    'company.streetPH': '123 Calle Principal',
    'company.suitePH': 'Opcional',
    'company.cityPH': 'Ciudad',
    'company.statePH': 'Estado',
    'company.zipPH': 'Código Postal',
    'company.helper': 'Puede ser tu domicilio, oficina o donde vayas a operar. Siempre puedes actualizarlo después.',

    // MembersStep
    'members.personN': 'Persona {n}',
    'members.remove': 'Eliminar',
    'members.firstName': 'Nombre',
    'members.lastName': 'Apellido',
    'members.titleRole': 'Título / Rol',
    'members.email': 'Correo Electrónico',
    'members.ownership': '% de Participación',
    'members.firstPH': 'Nombre',
    'members.lastPH': 'Apellido',
    'members.titlePH': 'Selecciona título...',
    'members.emailPH': 'correo@ejemplo.com',
    'members.addAnother': 'Agregar Otra Persona',
    'members.ownershipValid': 'La participación totaliza 100%.',
    'members.ownershipInvalid': 'La participación debe ser igual al 100%. Total actual: {total}%.',
    'members.sub': 'Agrega las personas que formarán parte de tu {entity}.',

    // PackageStep
    'package.title': 'Comienza a Ahorrar en Impuestos',
    'package.per6mo': 'cada 6 meses',
    'package.annualNote': '${price}/año — primer pago después de la formación + tarifas estatales',
    'package.savingsBadge': 'Ahorro Fiscal Estimado ~${amount}',
    'package.recommended': 'Recomendado',
    'package.selected': 'Seleccionado',
    'package.selectPlan': 'Seleccionar Plan',
    'package.filingFeeNote': 'Tarifa de registro estatal de {state}: ${fee} — vence hoy. Tu suscripción al plan comienza después del registro.',
    'package.comparePlans': 'Comparar Planes en Detalle',
    'package.colFeature': 'Característica',
    'package.colIndependent': 'Independiente',
    'package.colCovered': 'Cubierto',

    // CheckoutStep
    'checkout.title': 'Pago',
    'checkout.sub': 'Completa tu orden para iniciar el proceso de formación.',
    'checkout.editInfo': 'Editar Tu Información',
    'checkout.editInfoSub': 'Revisa y actualiza los detalles de tu negocio',
    'checkout.orderSummary': 'Resumen del Pedido',
    'checkout.stateFee': 'Tarifa de Registro Estatal de {state}',
    'checkout.dueToday': 'Vence hoy',
    'checkout.billedAfter': '${semi}/6mo (${annual}/año) — cobrado después de la formación',
    'checkout.firstPayment': '${annual}/año — primer pago vence hoy',
    'checkout.dueTodayLabel': 'Vence Hoy',
    'checkout.orCard': 'o paga con tarjeta',
    'checkout.nameOnCard': 'Nombre en la Tarjeta',
    'checkout.namePH': 'Nombre completo como aparece en la tarjeta',
    'checkout.sameAsOwner': 'Igual al propietario principal',
    'checkout.cardDetails': 'Datos de la Tarjeta',
    'checkout.billingAddress': 'Dirección de Facturación',
    'checkout.sameAsAddress': 'Igual a la dirección del negocio',
    'checkout.secureNote': 'Tu información de pago está protegida con cifrado SSL de 256 bits.',
    'checkout.modal.title': 'Editar Tu Información',
    'checkout.modal.bizStructure': 'Estructura del Negocio y Estado',
    'checkout.modal.bizAddress': 'Dirección del Negocio',
    'checkout.modal.entityType': 'Tipo de Entidad',
    'checkout.modal.stateFormation': 'Estado de Formación',
    'checkout.modal.entityName': 'Nombre de la Entidad',
    'checkout.modal.address': 'Dirección',
    'checkout.modal.plan': 'Plan',
    'checkout.modal.planCost': 'Costo del Plan',
    'checkout.modal.stateFee': 'Tarifa de Registro Estatal',
    'checkout.modal.terms': 'Al enviar este pedido, aceptas nuestros Términos de Servicio y Política de Privacidad.',
    'checkout.modal.done': 'Listo',
    'checkout.modal.personN': 'Persona {n}',
    'checkout.modal.title2': 'Título',
    'checkout.modal.email': 'Correo',
    'checkout.modal.ownership': 'Participación',
    'checkout.modal.selectedPlan': 'Plan Seleccionado',

    // TaxSavingsStep
    'tax.titleResults': 'Tu ahorro fiscal estimado',
    'tax.titleInitial': 'Encontremos tus ahorros fiscales ocultos',
    'tax.subResults': 'Basado en los ingresos y detalles que proporcionaste.',
    'tax.subEstimate': 'Responde 3 preguntas rápidas para estimar tus ahorros desbloqueados.',
    'tax.subDefault': 'Responde 3 preguntas rápidas y estimaremos cuánto más podrías ahorrar.',
    'tax.annualSavings': 'Ahorro Anual Estimado',
    'tax.seSavings': 'Ahorro en Impuesto de Trabajo Independiente',
    'tax.deductionSavings': 'Ahorro en Deducciones Adicionales',
    'tax.revenueYes': '¿Cuánto generas al año con tu 1099, trabajo independiente o gig (fuera de tu W-2)?',
    'tax.revenueNo': '¿Cuánto esperas generar al año con tu 1099, trabajo independiente o gig (fuera de tu W-2)?',
    'tax.revenueDefault': '¿Cuánto generas al año fuera de tu W-2?',
    'tax.teamLabel': '¿Cuántas personas trabajan para ti?',
    'tax.bracketLabel': 'Tramo Fiscal Efectivo',
    'tax.bracketHelper': 'Normalmente es 25%. Lo hemos estimado para ti.',
    'tax.editAssumptions': 'Editar Supuestos',
    'tax.calculateBtn': 'Calcular Mis Ahorros Fiscales',
    'tax.lockBtn': 'Asegurar Estos Ahorros',
    'tax.unlockBtn': 'Desbloquear Ahorros Fiscales',
    'tax.updateBtn': 'Actualizar Mis Ahorros',
    'tax.back': 'Atrás',
    'tax.scheduler.title': 'Agenda Tu Consulta de Ahorros Fiscales',
    'tax.scheduler.sub': 'Reúnete con un Consultor Fiscal para Pequeñas Empresas y aprende cómo desbloquear hasta',
    'tax.scheduler.subEnd': '/año en ahorros.',
    'tax.scheduler.advisorTitle': 'En tu consulta gratuita, tu asesor:',
    'tax.scheduler.i1': 'Revisará tu estructura de negocio actual y situación fiscal',
    'tax.scheduler.i2': 'Identificará estrategias para reducir el impuesto de trabajo independiente',
    'tax.scheduler.i3': 'Descubrirá deducciones que podrías estar perdiendo',
    'tax.scheduler.i4': 'Creará un plan personalizado para maximizar tus ahorros',
    'tax.scheduler.dateLabel': 'Fecha Preferida',
    'tax.scheduler.timeLabel': 'Hora Preferida',
    'tax.scheduler.confirmBtn': 'Confirmar Consulta',
    'tax.scheduler.confirmNote': 'Un Consultor Fiscal se pondrá en contacto para confirmar tu cita.',
    'tax.scheduler.back': 'Volver al Estimado de Ahorros',

    // NonProfitScheduleStep
    'nonprofit.title': 'Hablemos de Tu Organización Sin Fines de Lucro',
    'nonprofit.sub': 'La formación sin fines de lucro tiene requisitos únicos — desde el estatus exento de impuestos hasta la estructura de la junta. Nos encantaría conocer más sobre tus objetivos y guiarte en el proceso.',
    'nonprofit.coverTitle': 'En tu consulta gratuita, cubriremos:',
    'nonprofit.i1': 'La misión y objetivos de tu organización',
    'nonprofit.i2': 'Requisitos de estatus exento de impuestos (501(c)(3), etc.)',
    'nonprofit.i3': 'Estructura y gobernanza de la junta',
    'nonprofit.i4': 'Requisitos de registro específicos del estado',
    'nonprofit.i4State': 'Requisitos de registro específicos para {state}',
    'nonprofit.i5': 'Un plan de formación personalizado y cronograma',
    'nonprofit.scheduleBtn': 'Agendar una Consulta Gratuita',
    'nonprofit.orCall': 'o llámanos directamente',
    'nonprofit.callBtn': 'Llamar al 1-800-222-6868',
    'nonprofit.back': 'Volver a Selección de Entidad',

    // RegisteredAgentStep
    'agent.title': 'Agente Registrado',
    'agent.sub': 'Todo negocio necesita un agente registrado para recibir documentos legales en su nombre.',
    'agent.useOursTitle': 'Usar Nuestro Servicio',
    'agent.useOursPrice': '$99/año',
    'agent.useOursDesc': 'Serviremos como tu agente registrado por $99 al año, facturado anualmente después de la formación.',
    'agent.recommended': 'Recomendado',
    'agent.ownTitle': 'Proporcionaré el Mío',
    'agent.ownDesc': 'Designa tu propio agente registrado. Debe tener una dirección física en el estado de formación.',
    'agent.serviceTitle': 'Nuestro Servicio de Agente Registrado Incluye:',
    'agent.si1': 'Dirección física dedicada en tu estado de formación',
    'agent.si2': 'Recibir y reenviar toda la correspondencia legal',
    'agent.si3': 'Notificación digital el mismo día de los documentos notificados',
    'agent.si4': 'Recordatorios de cumplimiento para informes anuales y plazos',
    'agent.si5': 'Panel en línea para ver todos los documentos',
    'agent.agentName': 'Nombre del Agente',
    'agent.physAddr': 'Dirección Física',
    'agent.noPO': '(Sin apartados postales)',
    'agent.agentNamePH': 'Nombre completo o nombre de empresa',
    'agent.streetPH': 'Dirección',
    'agent.suitePH': 'Suite / Unidad',
    'agent.cityPH': 'Ciudad',
    'agent.statePH': 'Estado',
    'agent.zipPH': 'Código Postal',
    'agent.confirmBtn': 'Confirmar Agente Registrado',
  },
}

export function createT(lang) {
  return function t(key, vars = {}) {
    const str = strings[lang]?.[key] ?? strings.en[key] ?? key
    return Object.entries(vars).reduce(
      (s, [k, v]) => s.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v)),
      str
    )
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  return (
    <LanguageContext.Provider value={{ lang, setLang }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const { lang, setLang } = useContext(LanguageContext)
  const t = createT(lang)
  return { lang, setLang, t }
}

export default strings
